"use client"
import React, { useEffect, useMemo, useRef, useState } from "react"
import { ImagePlus, RefreshCw, Trash2, UploadCloud } from "lucide-react"
import type { Locale } from "@fotomax/shared"
import type { PhotoAssetView, PhotoUploadSessionView } from "../../lib/photo/contracts"
import { createPhotoClient } from "../../lib/photo/client"
import { MultipartUploader, restoreUploads, validateSelection } from "../../lib/photo/uploader"
type RowStatus = "queued" | "uploading" | "uploaded" | "failed"
type QueueRow = { id: string; name: string; bytes: number; status: RowStatus; progress: number; file?: File; sessionId?: string; error?: string }
const labels = {
  en: { add: "Add photos", heading: "Your photos", empty: "No photos added yet", uploaded: "Uploaded", uploading: "Uploading", queued: "Ready", failed: "Upload failed", retry: "Retry upload", choose: "Choose file to retry", remove: "Remove", total: "Overall upload progress", errors: { photo_asset_limit_exceeded: "A workspace can contain up to 500 photos.", photo_job_bytes_exceeded: "These photos exceed the 10 GB workspace limit.", photo_file_too_large: "This photo is too large.", photo_upload_failed: "Upload failed. Try again." } },
  "zh-HK": { add: "加入相片", heading: "你的相片", empty: "尚未加入相片", uploaded: "已上載", uploading: "上載中", queued: "準備上載", failed: "上載失敗", retry: "重新上載", choose: "選擇檔案重新上載", remove: "移除", total: "整體上載進度", errors: { photo_asset_limit_exceeded: "每個工作區最多可加入 500 張相片。", photo_job_bytes_exceeded: "相片總容量超過工作區 10 GB 上限。", photo_file_too_large: "此相片檔案太大。", photo_upload_failed: "上載失敗，請再試一次。" } },
} as const
export function PhotoUploader({ jobId, locale, assets = [] }: { jobId: string; locale: Locale; assets?: PhotoAssetView[] }) {
  const copy = labels[locale]; const storageKey = `fotomax:photo-queue:${jobId}`; const uploader = useMemo(() => new MultipartUploader(createPhotoClient()), [])
  const [rows, setRows] = useState<QueueRow[]>(() => restoreUploads({ id: jobId, locale, revision: 0, status: "uploading", assets }).map((item) => ({ ...item, progress: item.status === "uploaded" ? 100 : 0 })))
  const [hydrated, setHydrated] = useState(false); const [selectionError, setSelectionError] = useState<string | null>(null); const retryRefs = useRef<Record<string, HTMLButtonElement | null>>({})
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(storageKey) ?? "[]") as QueueRow[]; if (saved.length) setRows(saved.map((row) => ({ ...row, status: row.status === "uploading" ? "failed" : row.status, error: row.status === "uploading" ? "photo_upload_failed" : row.error }))) } catch {} setHydrated(true) }, [storageKey])
  useEffect(() => { if (hydrated) localStorage.setItem(storageKey, JSON.stringify(rows.map(({ file: _file, ...row }) => row))) }, [hydrated, rows, storageKey])
  const update = (id: string, patch: Partial<QueueRow>) => setRows((current) => current.map((row) => row.id === id ? { ...row, ...patch } : row))
  const message = (code?: string) => copy.errors[code as keyof typeof copy.errors] ?? copy.errors.photo_upload_failed
  async function run(row: QueueRow) { if (!row.file) return; update(row.id, { status: "uploading", error: undefined }); try { await uploader.upload(jobId, row.file, row.id, { onProgress: (progress) => update(row.id, { progress: progress.percent }), onSession: (session: PhotoUploadSessionView) => update(row.id, { sessionId: session.sessionId }) }); update(row.id, { status: "uploaded", progress: 100 }) } catch (error) { const code = error instanceof Error ? error.message : "photo_upload_failed"; update(row.id, { status: "failed", error: code }); requestAnimationFrame(() => retryRefs.current[row.id]?.focus()) } }
  function select(files: FileList | null) { const selected = Array.from(files ?? []); if (!selected.length) return; try { validateSelection(selected, rows.map((row) => ({ expected_bytes: row.bytes, status: row.status === "uploaded" ? "uploaded" : "uploading" }))) } catch (error) { setSelectionError(message(error instanceof Error ? error.message : undefined)); return }; setSelectionError(null); const additions = selected.map((file) => ({ id: crypto.randomUUID(), name: file.name, bytes: file.size, status: "queued" as const, progress: 0, file })); setRows((current) => [...current, ...additions]); additions.forEach((row) => void run(row)) }
  async function remove(row: QueueRow) { if (row.sessionId && row.status !== "uploaded") await uploader.abort(jobId, row.sessionId).catch(() => undefined); setRows((current) => current.filter((item) => item.id !== row.id)) }
  function replaceFile(row: QueueRow, files: FileList | null) { const file = files?.[0]; if (!file) return; if (file.name !== row.name || file.size !== row.bytes) { update(row.id, { error: "photo_upload_failed" }); return }; const next = { ...row, file }; update(row.id, { file }); void run(next) }
  const totalBytes = rows.reduce((sum, row) => sum + row.bytes, 0); const uploadedBytes = rows.reduce((sum, row) => sum + row.bytes * row.progress / 100, 0); const aggregate = totalBytes ? Math.round(uploadedBytes / totalBytes * 100) : 0
  return <section className="photo-uploader" aria-labelledby="photo-queue-heading"><div className="photo-uploader-toolbar"><div><p className="eyebrow">FotoMax</p><h2 id="photo-queue-heading">{copy.heading}</h2></div><label className="button primary photo-picker"><ImagePlus aria-hidden="true" size={19} />{copy.add}<input type="file" accept="image/jpeg,image/png,image/heic,image/heif" multiple onChange={(event) => select(event.currentTarget.files)} /></label></div>{selectionError ? <p className="photo-error" role="alert">{selectionError}</p> : null}<div className="photo-aggregate"><span>{copy.total}</span><strong>{aggregate}%</strong><progress value={aggregate} max={100}>{aggregate}%</progress></div>{rows.length ? <ul className="photo-queue">{rows.map((row) => <li className="photo-queue-row" key={row.id}><UploadCloud aria-hidden="true" size={22} /><div className="photo-file"><strong>{row.name}</strong><span>{formatBytes(row.bytes)} · {copy[row.status]}</span>{row.error ? <span className="photo-row-error" role="alert">{message(row.error)}</span> : null}</div><progress aria-label={`${row.name}: ${copy[row.status]}`} value={row.progress} max={100}>{row.progress}%</progress><span className="photo-percent" aria-live="polite">{row.progress}%</span><div className="photo-row-actions">{row.status === "failed" && row.file ? <button className="icon-button" type="button" ref={(node) => { retryRefs.current[row.id] = node }} onClick={() => void run(row)} title={copy.retry}><RefreshCw aria-hidden="true" size={18} /><span className="sr-only">{copy.retry}</span></button> : null}{row.status === "failed" && !row.file ? <label className="icon-button photo-retry-picker" title={copy.choose}><RefreshCw aria-hidden="true" size={18} /><span className="sr-only">{copy.choose}</span><input type="file" accept="image/jpeg,image/png,image/heic,image/heif" onChange={(event) => replaceFile(row, event.currentTarget.files)} /></label> : null}<button className="icon-button" type="button" onClick={() => void remove(row)} title={copy.remove}><Trash2 aria-hidden="true" size={18} /><span className="sr-only">{copy.remove}</span></button></div></li>)}</ul> : <div className="photo-empty"><UploadCloud aria-hidden="true" size={30} /><p>{copy.empty}</p></div>}</section>
}
function formatBytes(bytes: number): string { if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB` }
