import { describe, expect, it, vi } from "vitest"
import { DELETE } from "./[id]/assets/[assetId]/route"
function fixture(owner = "cus_1") {
  const asset = { id: "asset_1", job_id: "job_1", object_key: "private/key", status: "uploaded" }
  const service: Record<string, any> = { retrievePhotoJob: vi.fn(async () => ({ id: "job_1", customer_id: owner, status: "uploading" })), retrievePhotoAsset: vi.fn(async () => asset), listPhotoUploadSessions: vi.fn(async () => []), updatePhotoUploadSessions: vi.fn(async (input) => [{ id: input.selector.id, status: "aborted" }]), updatePhotoAssets: vi.fn(async () => [{ ...asset, status: "deleted" }]), withPhotoJobTransaction: vi.fn(async (callback) => callback({ transactionManager: {} })) }
  const storage: Record<string, any> = { abortMultipartUpload: vi.fn(async () => undefined), deletePrivateObjects: vi.fn(async () => undefined) }
  const req = { params: { id: "job_1", assetId: "asset_1" }, auth_context: { actor_id: "cus_1" }, headers: { get: () => null }, scope: { resolve: (name: string) => name.toLowerCase().includes("storage") ? storage : service } }; const res = { json: vi.fn() }
  return { asset, service, storage, req, res }
}
describe("owned photo asset delete", () => {
  it("durably releases the asset before deleting private bytes", async () => { const { service, storage, req, res } = fixture(); const order: string[] = []; service.updatePhotoAssets.mockImplementation(async () => { order.push("db"); return [{ id: "asset_1", status: "deleted", object_key: "private/key" }] }); storage.deletePrivateObjects.mockImplementation(async () => { order.push("provider") }); await DELETE(req, res); expect(order).toEqual(["db", "provider"]); expect(res.json).toHaveBeenCalledWith({ asset: { id: "asset_1", status: "deleted" } }) })
  it("leaves provider bytes untouched when the database transition fails", async () => { const { service, storage, req, res } = fixture(); service.withPhotoJobTransaction.mockRejectedValue(new Error("database unavailable")); await expect(DELETE(req, res)).rejects.toThrow("database unavailable"); expect(storage.deletePrivateObjects).not.toHaveBeenCalled() })
  it("keeps deleted state retryable when provider cleanup fails", async () => { const { service, storage, req, res } = fixture(); storage.deletePrivateObjects.mockRejectedValueOnce(new Error("provider unavailable")); await expect(DELETE(req, res)).rejects.toThrow("provider unavailable"); service.retrievePhotoAsset.mockResolvedValue({ id: "asset_1", job_id: "job_1", object_key: "private/key", status: "deleted" }); storage.deletePrivateObjects.mockResolvedValueOnce(undefined); await DELETE(req, res); expect(storage.deletePrivateObjects).toHaveBeenCalledTimes(2); expect(res.json).toHaveBeenCalledWith({ asset: { id: "asset_1", status: "deleted" } }) })
  it("does not swallow multipart abort failures", async () => { const { service, storage, req, res } = fixture(); service.listPhotoUploadSessions.mockResolvedValue([{ id: "session_1", provider_upload_id: "provider_1" }]); storage.abortMultipartUpload.mockRejectedValue(new Error("abort unavailable")); await expect(DELETE(req, res)).rejects.toThrow("abort unavailable"); expect(storage.deletePrivateObjects).not.toHaveBeenCalled() })
  it("conceals assets from another customer", async () => { const { req, res } = fixture("cus_other"); await expect(DELETE(req, res)).rejects.toThrow("photo_job_not_found") })
})
